name: Install CIRCT

inputs:
  version:
    description: 'version to install ("nightly" installs latest nightly)'
    default: 'default'
  github-token:
    description: 'The GitHub token used to download CIRCT nightly'
    required: true
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Download release `firtool` binary
      shell: bash
      if: inputs.version != 'nightly'
      run: |
        if [[ "${{ inputs.version }}" == "default" ]]; then
          export VERSION=`jq -r .version < ./etc/circt.json`
        else
          export VERSION="${{ inputs.version }}"
        fi
        mkdir circt
        wget -O - https://github.com/llvm/circt/releases/download/$VERSION/firtool-bin-linux-x64.tar.gz | tar -zx -C circt/ --strip-components 1

    - name: Download Latest Nighlty `firtool` binary
      shell: bash
      if: inputs.version == 'nightly'
      run: |
        ARTIFACT_NAME=firtool-bin-linux-x64.tar.gz
        ARTIFACT_ID=$(
          curl -L \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ inputs.github-token }}" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               "https://api.github.com/repos/llvm/circt/actions/artifacts?name=$ARTIFACT_NAME&per_page=1" | \
            jq '.artifacts[0].id')
        echo $ARTIFACT_ID
        curl -L \
             -H "Accept: application/vnd.github+json" \
             -H "Authorization: Bearer ${{ inputs.github-token }}" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             "https://api.github.com/repos/llvm/circt/actions/artifacts/$ARTIFACT_ID/zip" \
             --output download.zip
        mkdir circt/
        unzip -p download.zip | tar -zx -C circt/ --strip-components 1
        rm download.zip

    - shell: bash
      run: |
        echo "$(pwd)/circt/bin" >> $GITHUB_PATH
        ./circt/bin/firtool -version
